Trying to change orientation but getting error:
IllegalArgumentException: No view found for id 0x7f07003c (com.github.dddpaul.netcat:id/pager) for fragment ResultFragment

The reason is that retained ResultFragment stores reference to ViewPager in mContainer field.